### ISSUE TITLE
Examples with Observational data

### ISSUE THREAD

**Issue by XmataAdmin** [Minyus/causallift#17]
Hello Yusuke, first of all, I wanted to say that you have done a great job with the package. There are two points that stand out to me and I see that frequently as well:

- Observational data as opposed to randomized data.
- Trying to explain concepts in business terms
Do you have a sample example that shows CausalLift with observational data? Would love to see an example.
Thank you again,
--Muneer

**Comment by Minyus** [comment]
Yes, I prepared a demo using observational data at:  https://colab.research.google.com/github/Minyus/causallift/blob/master/notebooks/demo/CausalLift_demo.ipynb

In default, simulated observational dataset is used.
To use an actual observational dataset called "Lalonde", set `data = 'lalonde'` instead of `data = 'simulated_observational_data'`.

Lalonde dataset was used to evaluate propensity score in the paper: Dehejia, R., & Wahba, S. (1999). Causal Effects in Nonexperimental Studies: Reevaluating the Evaluation of Training Programs. Journal of the American Statistical Association, 94(448), 1053-1062. doi:10.2307/2669919

**Comment by mmubashir** [comment]
Great.  Thanks!
